// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBwf_axYRyz8tks8ja1paLbWCGrn39jqM',
    appId: '1:784537116270:web:59c18a1671b0194749107f',
    messagingSenderId: '784537116270',
    projectId: 'alastair-reader',
    authDomain: 'alastair-reader.firebaseapp.com',
    storageBucket: 'alastair-reader.firebasestorage.app',
    measurementId: 'G-S55QS0RDY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjAJixHMGKM54GmTibnFR7U9-d8-RbpNs',
    appId: '1:784537116270:android:dc336713ea04d50749107f',
    messagingSenderId: '784537116270',
    projectId: 'alastair-reader',
    storageBucket: 'alastair-reader.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4ZKPl1iDcwzuhtR_gepX_A_wR_tB4l6g',
    appId: '1:784537116270:ios:ab48eb8213cebdee49107f',
    messagingSenderId: '784537116270',
    projectId: 'alastair-reader',
    storageBucket: 'alastair-reader.firebasestorage.app',
    iosBundleId: 'com.example.rssClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4ZKPl1iDcwzuhtR_gepX_A_wR_tB4l6g',
    appId: '1:784537116270:ios:ab48eb8213cebdee49107f',
    messagingSenderId: '784537116270',
    projectId: 'alastair-reader',
    storageBucket: 'alastair-reader.firebasestorage.app',
    iosBundleId: 'com.example.rssClient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBwf_axYRyz8tks8ja1paLbWCGrn39jqM',
    appId: '1:784537116270:web:96c4dd826defc2d349107f',
    messagingSenderId: '784537116270',
    projectId: 'alastair-reader',
    authDomain: 'alastair-reader.firebaseapp.com',
    storageBucket: 'alastair-reader.firebasestorage.app',
    measurementId: 'G-HCKC3WXECL',
  );
}
